version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword

volumes:
  mongodb_data:

networks:
  mongodb_network: